In [8]:
#program to perform matrix multiplication and transformation using python
import numpy as np
a=np.array([[1,2,3],[1,2,4],[2,3,4]])
print("The matrix a is :\n",a)

b=np.array([[2,3,4],[1,2,3],[3,2,1]])
print("\nThe matrix b is:\n",b)

print("\n Multiplication of matrix a and b is:\n",np.dot(a,b))

print("\nTranspose of matrix b is\n",b.transpose())


The matrix a is :
 [[1 2 3]
 [1 2 4]
 [2 3 4]]

The matrix b is:
 [[2 3 4]
 [1 2 3]
 [3 2 1]]

 Multiplication of matrix a and b is:
 [[13 13 13]
 [16 15 14]
 [19 20 21]]

Transpose of matrix b is
 [[2 1 3]
 [3 2 2]
 [4 3 1]]
