In [6]:
#program to perform svd using python
import numpy as np
from scipy.linalg import svd

a=np.array([[1,2,3],[4,5,6],[3,2,4]])
print("The matrix a is:\n",a)

v,s,t=svd(a)  #to find svd

print("\n v= ",v)
print("\n s= ",s)
print("\n t= ",t)

e=(v @ np.diag(s) @t)
print("\n",e)

The matrix a is:
 [[1 2 3]
 [4 5 6]
 [3 2 4]]

 v=  [[-0.33639989  0.45240714  0.82593153]
 [-0.80581847  0.3155772  -0.50106649]
 [-0.48733122 -0.83410959  0.25839789]]

 s=  [10.87097278  1.13625135  0.72861765]

 t=  [[-0.46193358 -0.5221754  -0.71690321]
 [-0.6931678   0.71681418 -0.07547078]
 [-0.55329537 -0.46207174  0.69307571]]

 [[1. 2. 3.]
 [4. 5. 6.]
 [3. 2. 4.]]
